import '@styles/globals.scss'
import type { AppProps } from 'next/app'
import store from '@store/store'
import { Provider } from 'react-redux'
import Head from 'next/head'
import Layout from '@components/Layout/Layout'

const App = ({ Component, pageProps }: AppProps) => {
  console.log({...pageProps})
  return (
    <Provider store={store}>
      <Head>
        <title>Royal Spa Relax</title>
        <meta name="description" content="Generated by Royal Spa Relax" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </Provider>
  )
}

export default App

