import '@styles/globals.scss'
import type { AppProps } from 'next/app'
import store from '@store/store'
import { Provider } from 'react-redux'
import Header from '@components/Header/Header'
import Footer from '@components/Footer/Footer'
import Head from 'next/head'

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <Provider store={store}>
      <Head>
        <title>Royal Spa Relax</title>
        <meta name="description" content="Generated by Royal Spa Relax" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Component {...pageProps} />
      <Footer/>
    </Provider>
  )
}

export default App

